version: '3.1'

services:
  app:
    build: .
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGODB_URI: mongodb://mongo/app

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

volumes:
  mongo-data:
